In [1]:
import os
os.chdir("C:/Users/anton/Desktop/University/AI_Lab/Git_repo")

In [2]:
import pandas as pd
import numpy as np
import torch
from fix_data import add_label_T
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [7]:
df = pd.read_csv("data/SmartSeq/HCC1806_SmartS_Unfiltered_Data.txt", sep=" ")
df = add_label_T(df, dropname=True)
df

,WASH7P,CICP27,DDX11L17,WASH9P,OR4F29,MTND1P23,MTND2P28,MTCO1P12,MTCO2P12,MTATP8P1,...,MT-TS2,MT-TL2,MT-ND5,MT-ND6,MT-TE,MT-CYB,MT-TT,MT-TP,MAFIP,label
0,0,0,0,0,2,250,54,1740,6,1,...,5,15,3852,900,22,4208,26,66,0,1
1,0,0,0,0,0,424,100,2340,5,1,...,29,36,7457,1439,43,6491,62,71,4,1
2,0,0,0,0,0,11,0,22,0,0,...,0,0,93,12,0,25,0,1,0,0
3,0,0,0,0,0,63,16,1020,3,0,...,17,8,1479,234,0,4819,11,3,7,0
4,0,0,0,0,0,27,3,303,0,0,...,0,3,303,33,0,310,4,9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,0,0,0,1,0,146,47,961,1,0,...,17,11,2926,423,26,3719,42,48,3,1
239,0,0,0,0,0,37,6,372,0,0,...,1,3,688,114,1,984,1,18,0,1
240,0,0,0,1,0,83,30,1128,4,0,...,6,23,2999,486,4,2256,15,36,2,0
241,0,0,0,0,0,47,7,258,1,0,...,3,3,611,75,4,981,6,8,1,1
242,0,0,0,0,0,249,38,980,0,0,...,3,15,2460,513,20,2039,34,79,5,1

In [28]:
X_train, X_test, y_train, y_test = train_test_split(df.drop("label", axis=1), df["label"], test_size=0.2)
clf = LogisticRegression(penalty="l1", C=0.1, solver="liblinear")
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))
coef = clf.coef_.tolist()[0]
n = 0
for c in coef:
    if abs(c) > 0:
        n += 1
n

1.0

156